# -*- coding: utf-8 -*-
"""deeplearning1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-MgRT6DBbWCXGpad4Lg2k8YJieGVOG5i
"""

from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

def GoogleDriveAuth(ID):
    auth.authenticate_user()
    gauth = GoogleAuth()
    gauth.credentials = GoogleCredentials.get_application_default()
    drive = GoogleDrive(gauth)
    file = drive.CreateFile({'id': ID})
    return file


File_ID = '1eNfKBri8eA1_1pOi_5saN_jzKDBsuXU4'
file_name = GoogleDriveAuth(File_ID)
file_name.GetContentFile('data_carsmall.xslx')

import pandas as pd
import numpy as np

data = pd.read_excel('data_carsmall.xslx')
df = pd.DataFrame(data)
df.drop(df.index[0])
#df = df.drop(77)#delete X4
df = df.drop(0)#delete x4
#test = df[df.isnull().any(axis=1)]
test=df[pd.isnull(df['y'])]
train = df.dropna(subset=['y'])

train = train.fillna(0)
#print(train)
mean=train.mean(axis=0)
Y_mean=(mean['y'])
std=train.std(axis=0)
Y_Std=(std['y'])
train=train-mean
train=train.div(std)
train.insert(0, 'x0', 1)

#print(test)
orgX_test=test[['x1','x2','x3','x4','x5']]
mean=test.mean(axis=0)
std=test.std(axis=0)
test=test-mean
test=test.div(std)
test.insert(0, 'x0', 1)

alpha=0.025
m=train.x0.count()

X=train[['x0','x1','x2','x3','x4','x5']]
Y=train['y']
theta=[0 for i in range(6)]

X=X.astype(float)
for i in range (1000):
  h_theta=np.matmul(X,np.transpose(theta))
  sub=h_theta-Y
  sub=sub.astype(float)
  theta=theta-(np.matmul(np.transpose(sub),X))*(alpha/m)  



X_test=test[['x0','x1','x2','x3','x4','x5']]
X_test=X_test.astype(float)
ans=np.matmul(X_test,np.transpose(theta))
ans=(ans*Y_Std)+Y_mean
orgX_test["y"] = ans
print(orgX_test)

test

!pip install pydrive

X.shape

len(theta)

theta

X

